Models/AIImage.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace WDP2024Assignment2.Models
{
    public class AIImage
    {
        public AIImage () 
        {
            Prompt = "";
            ImageGenerator = "";
            Filename = "";
            canIncreaseLike = true;
        }
        [Required]
        public int Id { get; set; }
        [Required]
        public string Prompt { get; set; }
        [Required]
        [Display(Name = "Image Generator")]
        public string ImageGenerator { get; set; }
        [Display(Name = "Upload Date")]
        public DateTime UploadDate { get; set; }
        public string Filename { get; set; }
        public int Like { get; set; }
        public bool canIncreaseLike { get; set; }
    }
}

Controllers/AIImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WDP2024Assignment2.Data;
using WDP2024Assignment2.Models;

using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace WDP2024Assignment2.Controllers
{
    public class AIImagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public AIImagesController(ApplicationDbContext context, IHostingEnvironment hostingEnv)
        {
            _context = context;
            _hostingEnv = hostingEnv;
        }

        // GET: AIImages
        public async Task<IActionResult> Index()
        {
            return View(await _context.AIImage.OrderByDescending(img => img.Like).ToListAsync());
        }

        // GET: AIImages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aIImage = await _context.AIImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aIImage == null)
            {
                return NotFound();
            }

            return View(aIImage);
        }

        // GET: AIImages/Create
        [Authorize]
        public IActionResult Create()
        {
            AIImage aIImage = new AIImage();
            aIImage.UploadDate = DateTime.Now;
            aIImage.Like = 0;

            return View(aIImage);
        }

        // POST: AIImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Prompt,ImageGenerator,UploadDate,Filename,Like,canIncreaseLike")] AIImage aIImage, UploadFile uploadFile)
        {
            if (uploadFile.File != null)
            {
                var fileName = Path.GetFileName(uploadFile.File.FileName);
                var filePath = Path.Combine(_hostingEnv.WebRootPath, "uploads", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await uploadFile.File.CopyToAsync(fileStream);
                }

                aIImage.Filename = fileName;
            }


            if (ModelState.IsValid)
            {
                _context.Add(aIImage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            return View(aIImage);
        }

        // GET: AIImages/Edit/5

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aIImage = await _context.AIImage.FindAsync(id);
            if (aIImage == null)
            {
                return NotFound();
            }
            else{
                aIImage.UploadDate = DateTime.Now;

            }
            return View(aIImage);
        }

        // POST: AIImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Prompt,ImageGenerator,UploadDate,Filename,Like,canIncreaseLike")] AIImage aIImage, UploadFile uploadFile)
        {
            if (id != aIImage.Id)
            {
                return NotFound();
            }

            if (uploadFile.File != null)
            {
                var fileName = Path.GetFileName(uploadFile.File.FileName);
                var filePath = Path.Combine(_hostingEnv.WebRootPath, "uploads", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await uploadFile.File.CopyToAsync(fileStream);
                }

                aIImage.Filename = fileName;
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aIImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AIImageExists(aIImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aIImage);
        }

        // GET: AIImages/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aIImage = await _context.AIImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aIImage == null)
            {
                return NotFound();
            }

            return View(aIImage);
        }

        // POST: AIImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aIImage = await _context.AIImage.FindAsync(id);
            if (aIImage != null)
            {
                _context.AIImage.Remove(aIImage);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AIImageExists(int id)
        {
            return _context.AIImage.Any(e => e.Id == id);
        }

        [Authorize]
        public async Task<IActionResult> IncreaseLike(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var aIImage = await _context.AIImage.FindAsync(id);
            if (aIImage == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (aIImage.canIncreaseLike){
                        aIImage.Like++;
                        aIImage.canIncreaseLike = false;
                        _context.Update(aIImage);
                        await _context.SaveChangesAsync();

                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AIImageExists(aIImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/AIImages/Create.cshtml
@model WDP2024Assignment2.Models.AIImage

@{
    ViewData["Title"] = "Create";
    ViewData["css-link"] = "~/css/create.css";
}

    


<div class="wrapper">
    <h1>Upload AI images</h1>
    
    
    
    <div class="row px-5">
        <div class="col-md-8 pr-2 col-sm-12 col-12">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Prompt" class="control-label text-white"></label>
                    <textarea asp-for="Prompt" class="form-control" rows="5" name="prompt"></textarea>
                    <span asp-validation-for="Prompt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageGenerator" class="control-label text-white"></label>
                    <input asp-for="ImageGenerator" class="form-control" />
                    <span asp-validation-for="ImageGenerator" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UploadDate" class="control-label text-white"></label>
                    <input asp-for="UploadDate" class="form-control" readonly/>
                    <span asp-validation-for="UploadDate" class="text-danger"></span>
                </div>
    
                <div class="form-group">
                    <label asp-for="Like" class="control-label text-white"></label>
                    <input asp-for="Like" class="form-control" readonly value="0" />
                    <span asp-validation-for="Like" class="text-danger"></span>
                </div>
               <div class="form-group">
                <label class="control-label text-white">Upload image file</label>
                <input type="file" name="file" class="form-control">
    
    
               </div>
               <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            
                
            </form>
            
        </div>
        <div class="ibm-img col-md-4 col-12 col-sm-12">
            
        </div>

        <a class="text-muted" asp-action="Index">Back to List</a>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AIImages/Delete.cshtml
@model WDP2024Assignment2.Models.AIImage

@{
    ViewData["Title"] = "Delete";
    ViewData["css-link"] = "~/css/delete.css";
}

<div class="wrapper">
    <h1>Delete AI Image</h1>
    
    <div class="r_u_sure">
        <h3>Are you sure you want to delete this?</h3>
        <h4>AIImage</h4>
    </div>
        
    <div>
        
        <dl class="row">
            <dt class = "col-sm-2 text-white">
                @Html.DisplayNameFor(model => model.Prompt)
            </dt>
            <dd class = "col-sm-10 text-white">
                @Html.DisplayFor(model => model.Prompt)
            </dd>
            <dt class = "col-sm-2 text-white">
                @Html.DisplayNameFor(model => model.ImageGenerator)
            </dt>
            <dd class = "col-sm-10 text-white">
                @Html.DisplayFor(model => model.ImageGenerator)
            </dd>
            <dt class = "col-sm-2 text-white" >
                @Html.DisplayNameFor(model => model.UploadDate)
            </dt>
            <dd class = "col-sm-10 text-white">
                @Html.DisplayFor(model => model.UploadDate)
            </dd>
            <dt class = "col-sm-2 text-white">
                @Html.DisplayNameFor(model => model.Filename)
            </dt>
            <dd class = "col-sm-10 text-white">
                @Html.DisplayFor(model => model.Filename)
            </dd>
            <dt class = "col-sm-2 text-white">
                @Html.DisplayNameFor(model => model.Like)
            </dt>
            <dd class = "col-sm-10 text-white">
                @Html.DisplayFor(model => model.Like)
            </dd>
            <dt class = "col-sm-2 text-white">
                @Html.DisplayNameFor(model => model.canIncreaseLike)
            </dt>
        </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index" class="text-muted">Back to List</a>
        </form>
    </div>
</div>

Views/AIImages/Details.cshtml
@model WDP2024Assignment2.Models.AIImage

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AIImage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prompt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prompt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageGenerator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageGenerator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UploadDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Like)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Like)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.canIncreaseLike)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.canIncreaseLike)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/AIImages/Edit.cshtml
@model WDP2024Assignment2.Models.AIImage

@{
    ViewData["Title"] = "Edit";
    ViewData["css-link"] = "~/css/edit.css";
}

<div class="bg">
    <h1>Edit AI Image</h1>


    <div class="row wrapper">
        <div class="col-md-8 col-sm-12 col-12">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="Filename" />
                <div class="form-group">
                    <label asp-for="Prompt" class="control-label text-white"></label>
                    <textarea asp-for="Prompt" class="form-control" rows="5" name="prompt"></textarea>
                    <span asp-validation-for="Prompt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageGenerator" class="control-label text-white"></label>
                    <input asp-for="ImageGenerator" class="form-control" />
                    <span asp-validation-for="ImageGenerator" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UploadDate" class="control-label text-white"></label>
                    <input asp-for="UploadDate" class="form-control" readonly />
                    <span asp-validation-for="UploadDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Like" class="control-label text-white"></label>
                    <input asp-for="Like" class="form-control" readonly />
                    <span asp-validation-for="Like" class="text-danger"></span>
                </div>

                <div class="form-group">
                <label class="control-label text-white">Upload image file</label>
                <input type="file" name="file" class="form-control">
    
    
               </div>
                

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
 

            </form>
            
        </div>
        <div class="col-md-4 col-sm-12 col-12 img-container">
            <img src="~/uploads/@Model.Filename" alt="@Model.Filename">
        </div>

        <a asp-action="Index" class="text-muted">Back to List</a>

    </div>


</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/AIImages/Index.cshtml
@model IEnumerable<WDP2024Assignment2.Models.AIImage>

@{
    ViewData["Title"] = "Index";
    ViewData["css-link"] = "~/css/aiimages.css";
}

<div class="heading">
    <h1>
        List of AI Images
    </h1>
    <a class="nav-link text-muted" asp-area="" asp-controller="AIImages" asp-action="Create">Click here to upload a new
        AI image</a>


</div>

@{
    int i = 0;
    foreach (var item in Model)
    {
        @if (i % 2 == 0)
        {
            <div class="even-section row">
                <div id='@item.Filename' class="col-md-4 col-sm-12 col-12 bg-ai-img">

                </div>
                <div class="col-md-8 col-sm-12 col-12  yellow-bg">
                    <h3>@item.ImageGenerator</h3>
                    <p>@item.Prompt
                    </p>
                    @{
                        if (User.Identity.IsAuthenticated){
                            <a asp-action="IncreaseLike" asp-route-id="@item.Id" class="btn btn-primary">Like (@item.Like)</a>
                            if (User.IsInRole("admin"))
{
<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
}

                        }
                    }
                    
                    
                </div>
            </div>
        }
        else
        {
            <div class="odd-section row">

                <div class="col-md-8 blue-bg col-sm-12 col-12">
                    <h3>@item.ImageGenerator</h3>
                    <p>@item.Prompt
                    </p>
                    @{
                        if (User.Identity.IsAuthenticated){
                            <a asp-action="IncreaseLike" asp-route-id="@item.Id" class="btn btn-primary">Like (@item.Like)</a>
                            if (User.IsInRole("admin"))
{
<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
}

                        }
                    }
                </div>

                <div id='@item.Filename' class="col-md-4 bg-ai-img col-sm-12 col-12">

                </div>
            </div>
            @* The same two <div> elements above but in reverse order *@
        }
        i = i + 1;
    }
}